import {
  FIELD_LABELS_ORGANIZATION, FIELD_LABELS_FACILITY, FIELD_LABELS_ROLE, FIELD_LABELS_USER,
  FIELD_LABELS_USER_FACILITY, FIELD_LABELS_DEPARTMENT, FIELD_LABELS_EMPLOYEE, FIELD_LABELS_FEATURE_MODULE,
  FIELD_LABELS_FEATURE_ACCESS, FIELD_LABELS_VITAL, FIELD_LABELS_CONSULTATION_STAFF, FIELD_LABELS_PATIENT,
  FIELD_LABELS_BILLABLE_ITEM_PRICE_HISTORY, FIELD_LABELS_FACILITY_BRANDING, FIELD_LABELS_LETTERHEAD_TEMPLATE,
  FIELD_LABELS_ORGANIZATION_BRANDING, FIELD_LABELS_PLAN, FIELD_LABELS_STOCK_REQUEST, FIELD_LABELS_STOCK_REQUEST_ITEM,
  FIELD_LABELS_BILLABLE_ITEM, FIELD_LABELS_CONSULTATION, FIELD_LABELS_DEPOSIT, FIELD_LABELS_INVOICE_ITEM,
  FIELD_LABELS_REFUND, FIELD_LABELS_REFUND_DEPOSIT, FIELD_LABELS_REGISTRATION_LOG, FIELD_LABELS_PLAN_MODULE, FIELD_LABELS_CENTRAL_STOCK,
  FIELD_LABELS_MASTER_ITEM, FIELD_LABELS_SUPPLIER, FIELD_LABELS_MASTER_ITEM_CATEGORY, FIELD_LABELS_STOCK_ADJUSTMENT,
  FIELD_LABELS_APPOINTMENT, FIELD_LABELS_LAB_REQUEST, FIELD_LABELS_LAB_REQUEST_ITEM, FIELD_LABELS_PRESCRIPTION,
  FIELD_LABELS_LAB_SUPPLY, FIELD_LABELS_PRESCRIPTION_ITEM, FIELD_LABELS_SURGERY, FIELD_LABELS_BED,
  FIELD_LABELS_EMPLOYEE_SHIFT, FIELD_LABELS_ACCESS_VIOLATION_LOG, FIELD_LABELS_DELIVERY_RECORD, FIELD_LABELS_MATERNITY_VISIT,
  FIELD_LABELS_PHARMACY_TRANSACTION, FIELD_LABELS_SYSTEM_AUDIT_LOG, FIELD_LABELS_INSURANCE_CLAIM, FIELD_LABELS_NEWBORN_RECORD,
  FIELD_LABELS_PROCEDURE_RECORD, FIELD_LABELS_ROOM, FIELD_LABELS_LOGIN_AUDIT, FIELD_LABELS_NURSING_NOTE,
  FIELD_LABELS_DISCOUNT, FIELD_LABELS_DISCOUNT_WAIVER, FIELD_LABELS_DISCOUNT_POLICY,  // ✅ Added
  FIELD_LABELS_INSURANCE_PREAUTHORIZATION, FIELD_LABELS_LAB_RESULT, FIELD_LABELS_RADIOLOGY_RECORD,
  FIELD_LABELS_ULTRASOUND_RECORD, FIELD_LABELS_INVOICE, FIELD_LABELS_INSURANCE_PROVIDER, FIELD_LABELS_RECOMMENDATION,
  FIELD_LABELS_MEDICAL_RECORD, FIELD_LABELS_WARD, FIELD_LABELS_ADMISSION, FIELD_LABELS_CURRENCY_RATE,
  FIELD_LABELS_AUTO_BILLING_RULE, FIELD_LABELS_MESSAGE, FIELD_LABELS_MESSAGE_ATTACHMENT, FIELD_LABELS_CONVERSATION,
  FIELD_LABELS_TRIAGE_RECORD, FIELD_LABELS_PAYMENT, FIELD_LABELS_ORGANIZATION_PLAN, FIELD_LABELS_EKG_RECORD,
  FIELD_LABELS_DEPARTMENT_STOCK,   FIELD_LABELS_PERMISSION, FIELD_LABELS_ROLE_PERMISSION,
  FIELD_LABELS_PATIENT_CHART_CACHE, FIELD_LABELS_PATIENT_CHART_NOTE, FIELD_LABELS_PATIENT_CHART_VIEW_LOG,
  FIELD_LABELS_FINANCIAL_LEDGER, FIELD_LABELS_REFUND_TRANSACTION
} from "./fieldLabels.js";
import {
  FIELD_ORDER_ORGANIZATION, FIELD_ORDER_FACILITY, FIELD_ORDER_ROLE, FIELD_ORDER_USER,
  FIELD_ORDER_USER_FACILITY, FIELD_ORDER_DEPARTMENT, FIELD_ORDER_EMPLOYEE, FIELD_ORDER_FEATURE_MODULE,
  FIELD_ORDER_FEATURE_ACCESS, FIELD_ORDER_VITAL, FIELD_ORDER_CONSULTATION_STAFF, FIELD_ORDER_PATIENT,
  FIELD_ORDER_BILLABLE_ITEM_PRICE_HISTORY, FIELD_ORDER_FACILITY_BRANDING, FIELD_ORDER_LETTERHEAD_TEMPLATE,
  FIELD_ORDER_ORGANIZATION_BRANDING, FIELD_ORDER_PLAN, FIELD_ORDER_STOCK_REQUEST, FIELD_ORDER_STOCK_REQUEST_ITEM,
  FIELD_ORDER_BILLABLE_ITEM, FIELD_ORDER_CONSULTATION, FIELD_ORDER_DEPOSIT, FIELD_ORDER_INVOICE_ITEM,
  FIELD_ORDER_REFUND, FIELD_ORDER_REFUND_DEPOSIT, FIELD_ORDER_REGISTRATION_LOG, FIELD_ORDER_PLAN_MODULE, FIELD_ORDER_CENTRAL_STOCK,
  FIELD_ORDER_MASTER_ITEM, FIELD_ORDER_SUPPLIER, FIELD_ORDER_MASTER_ITEM_CATEGORY, FIELD_ORDER_STOCK_ADJUSTMENT,
  FIELD_ORDER_APPOINTMENT, FIELD_ORDER_LAB_REQUEST, FIELD_ORDER_LAB_REQUEST_ITEM, FIELD_ORDER_PRESCRIPTION,
  FIELD_ORDER_LAB_SUPPLY, FIELD_ORDER_PRESCRIPTION_ITEM, FIELD_ORDER_SURGERY, FIELD_ORDER_BED,
  FIELD_ORDER_EMPLOYEE_SHIFT, FIELD_ORDER_ACCESS_VIOLATION_LOG, FIELD_ORDER_DELIVERY_RECORD, FIELD_ORDER_MATERNITY_VISIT,
  FIELD_ORDER_PHARMACY_TRANSACTION, FIELD_ORDER_SYSTEM_AUDIT_LOG, FIELD_ORDER_INSURANCE_CLAIM, FIELD_ORDER_NEWBORN_RECORD,
  FIELD_ORDER_PROCEDURE_RECORD, FIELD_ORDER_ROOM, FIELD_ORDER_LOGIN_AUDIT, FIELD_ORDER_NURSING_NOTE,
  FIELD_ORDER_DISCOUNT, FIELD_ORDER_DISCOUNT_WAIVER, FIELD_ORDER_DISCOUNT_POLICY,  // ✅ Added
  FIELD_ORDER_INSURANCE_PREAUTHORIZATION, FIELD_ORDER_LAB_RESULT, FIELD_ORDER_RADIOLOGY_RECORD,
  FIELD_ORDER_ULTRASOUND_RECORD, FIELD_ORDER_INVOICE, FIELD_ORDER_INSURANCE_PROVIDER, FIELD_ORDER_RECOMMENDATION,
  FIELD_ORDER_MEDICAL_RECORD, FIELD_ORDER_WARD, FIELD_ORDER_ADMISSION, FIELD_ORDER_CURRENCY_RATE,
  FIELD_ORDER_AUTO_BILLING_RULE, FIELD_ORDER_MESSAGE, FIELD_ORDER_MESSAGE_ATTACHMENT, FIELD_ORDER_CONVERSATION,
  FIELD_ORDER_TRIAGE_RECORD, FIELD_ORDER_PAYMENT, FIELD_ORDER_ORGANIZATION_PLAN, FIELD_ORDER_EKG_RECORD,
  FIELD_ORDER_DEPARTMENT_STOCK, FIELD_ORDER_REFUND_TRANSACTION,   FIELD_ORDER_PERMISSION, FIELD_ORDER_ROLE_PERMISSION,
  FIELD_ORDER_PATIENT_CHART_CACHE, FIELD_ORDER_PATIENT_CHART_NOTE, FIELD_ORDER_PATIENT_CHART_VIEW_LOG,
  FIELD_ORDER_FINANCIAL_LEDGER, 

} from "./fieldOrder.js";
import {
  FIELD_DEFAULTS_ORGANIZATION, FIELD_DEFAULTS_FACILITY, FIELD_DEFAULTS_ROLE, FIELD_DEFAULTS_USER,
  FIELD_DEFAULTS_USER_FACILITY, FIELD_DEFAULTS_DEPARTMENT, FIELD_DEFAULTS_EMPLOYEE, FIELD_DEFAULTS_FEATURE_MODULE,
  FIELD_DEFAULTS_FEATURE_ACCESS, FIELD_DEFAULTS_VITAL, FIELD_DEFAULTS_CONSULTATION_STAFF, FIELD_DEFAULTS_PATIENT,
  FIELD_DEFAULTS_BILLABLE_ITEM_PRICE_HISTORY, FIELD_DEFAULTS_FACILITY_BRANDING, FIELD_DEFAULTS_LETTERHEAD_TEMPLATE,
  FIELD_DEFAULTS_ORGANIZATION_BRANDING, FIELD_DEFAULTS_PLAN, FIELD_DEFAULTS_STOCK_REQUEST, FIELD_DEFAULTS_STOCK_REQUEST_ITEM,
  FIELD_DEFAULTS_BILLABLE_ITEM, FIELD_DEFAULTS_CONSULTATION, FIELD_DEFAULTS_DEPOSIT, FIELD_DEFAULTS_INVOICE_ITEM,
  FIELD_DEFAULTS_REFUND, FIELD_DEFAULTS_REFUND_DEPOSIT, FIELD_DEFAULTS_REGISTRATION_LOG, FIELD_DEFAULTS_PLAN_MODULE, FIELD_DEFAULTS_CENTRAL_STOCK,
  FIELD_DEFAULTS_MASTER_ITEM, FIELD_DEFAULTS_SUPPLIER, FIELD_DEFAULTS_MASTER_ITEM_CATEGORY, FIELD_DEFAULTS_STOCK_ADJUSTMENT,
  FIELD_DEFAULTS_APPOINTMENT, FIELD_DEFAULTS_LAB_REQUEST, FIELD_DEFAULTS_LAB_REQUEST_ITEM, FIELD_DEFAULTS_PRESCRIPTION,
  FIELD_DEFAULTS_LAB_SUPPLY, FIELD_DEFAULTS_PRESCRIPTION_ITEM, FIELD_DEFAULTS_SURGERY, FIELD_DEFAULTS_BED,
  FIELD_DEFAULTS_EMPLOYEE_SHIFT, FIELD_DEFAULTS_ACCESS_VIOLATION_LOG, FIELD_DEFAULTS_DELIVERY_RECORD, FIELD_DEFAULTS_MATERNITY_VISIT,
  FIELD_DEFAULTS_PHARMACY_TRANSACTION, FIELD_DEFAULTS_SYSTEM_AUDIT_LOG, FIELD_DEFAULTS_INSURANCE_CLAIM, FIELD_DEFAULTS_NEWBORN_RECORD,
  FIELD_DEFAULTS_PROCEDURE_RECORD, FIELD_DEFAULTS_ROOM, FIELD_DEFAULTS_LOGIN_AUDIT, FIELD_DEFAULTS_NURSING_NOTE,
  FIELD_DEFAULTS_DISCOUNT, FIELD_DEFAULTS_DISCOUNT_WAIVER, FIELD_DEFAULTS_DISCOUNT_POLICY,  // ✅ Added
  FIELD_DEFAULTS_INSURANCE_PREAUTHORIZATION, FIELD_DEFAULTS_LAB_RESULT, FIELD_DEFAULTS_RADIOLOGY_RECORD,
  FIELD_DEFAULTS_ULTRASOUND_RECORD, FIELD_DEFAULTS_INVOICE, FIELD_DEFAULTS_INSURANCE_PROVIDER, FIELD_DEFAULTS_RECOMMENDATION,
  FIELD_DEFAULTS_MEDICAL_RECORD, FIELD_DEFAULTS_WARD, FIELD_DEFAULTS_ADMISSION, FIELD_DEFAULTS_CURRENCY_RATE,
  FIELD_DEFAULTS_AUTO_BILLING_RULE, FIELD_DEFAULTS_MESSAGE, FIELD_DEFAULTS_MESSAGE_ATTACHMENT, FIELD_DEFAULTS_CONVERSATION,
  FIELD_DEFAULTS_TRIAGE_RECORD, FIELD_DEFAULTS_PAYMENT, FIELD_DEFAULTS_ORGANIZATION_PLAN, FIELD_DEFAULTS_EKG_RECORD,
  FIELD_DEFAULTS_DEPARTMENT_STOCK, FIELD_DEFAULTS_REFUND_TRANSACTION,   FIELD_DEFAULTS_PERMISSION, FIELD_DEFAULTS_ROLE_PERMISSION,
  FIELD_DEFAULTS_PATIENT_CHART_CACHE, FIELD_DEFAULTS_PATIENT_CHART_NOTE, FIELD_DEFAULTS_PATIENT_CHART_VIEW_LOG,
  FIELD_DEFAULTS_FINANCIAL_LEDGER, 

} from "./fieldDefaults.js";
import {
  FIELD_VISIBILITY_ORGANIZATION, FIELD_VISIBILITY_FACILITY, FIELD_VISIBILITY_ROLE, FIELD_VISIBILITY_USER,
  FIELD_VISIBILITY_USER_FACILITY, FIELD_VISIBILITY_DEPARTMENT, FIELD_VISIBILITY_EMPLOYEE, FIELD_VISIBILITY_FEATURE_MODULE,
  FIELD_VISIBILITY_FEATURE_ACCESS, FIELD_VISIBILITY_VITAL, FIELD_VISIBILITY_CONSULTATION_STAFF, FIELD_VISIBILITY_PATIENT,
  FIELD_VISIBILITY_BILLABLE_ITEM_PRICE_HISTORY, FIELD_VISIBILITY_FACILITY_BRANDING, FIELD_VISIBILITY_LETTERHEAD_TEMPLATE,
  FIELD_VISIBILITY_ORGANIZATION_BRANDING, FIELD_VISIBILITY_PLAN, FIELD_VISIBILITY_STOCK_REQUEST, FIELD_VISIBILITY_STOCK_REQUEST_ITEM,
  FIELD_VISIBILITY_BILLABLE_ITEM, FIELD_VISIBILITY_CONSULTATION, FIELD_VISIBILITY_DEPOSIT, FIELD_VISIBILITY_INVOICE_ITEM,
  FIELD_VISIBILITY_REFUND, FIELD_VISIBILITY_REFUND_DEPOSIT, FIELD_VISIBILITY_REGISTRATION_LOG, FIELD_VISIBILITY_PLAN_MODULE, FIELD_VISIBILITY_CENTRAL_STOCK,
  FIELD_VISIBILITY_MASTER_ITEM, FIELD_VISIBILITY_SUPPLIER, FIELD_VISIBILITY_MASTER_ITEM_CATEGORY, FIELD_VISIBILITY_STOCK_ADJUSTMENT,
  FIELD_VISIBILITY_APPOINTMENT, FIELD_VISIBILITY_LAB_REQUEST, FIELD_VISIBILITY_LAB_REQUEST_ITEM, FIELD_VISIBILITY_PRESCRIPTION,
  FIELD_VISIBILITY_PRESCRIPTION_ITEM, FIELD_VISIBILITY_LAB_SUPPLY, FIELD_VISIBILITY_SURGERY, FIELD_VISIBILITY_BED,
  FIELD_VISIBILITY_EMPLOYEE_SHIFT, FIELD_VISIBILITY_ACCESS_VIOLATION_LOG, FIELD_VISIBILITY_DELIVERY_RECORD, FIELD_VISIBILITY_MATERNITY_VISIT,
  FIELD_VISIBILITY_PHARMACY_TRANSACTION, FIELD_VISIBILITY_SYSTEM_AUDIT_LOG, FIELD_VISIBILITY_INSURANCE_CLAIM, FIELD_VISIBILITY_NEWBORN_RECORD,
  FIELD_VISIBILITY_PROCEDURE_RECORD, FIELD_VISIBILITY_ROOM, FIELD_VISIBILITY_LOGIN_AUDIT, FIELD_VISIBILITY_NURSING_NOTE,
  FIELD_VISIBILITY_DISCOUNT, FIELD_VISIBILITY_DISCOUNT_WAIVER, FIELD_VISIBILITY_DISCOUNT_POLICY,  // ✅ Added
  FIELD_VISIBILITY_INSURANCE_PREAUTHORIZATION, FIELD_VISIBILITY_LAB_RESULT, FIELD_VISIBILITY_RADIOLOGY_RECORD,
  FIELD_VISIBILITY_ULTRASOUND_RECORD, FIELD_VISIBILITY_INVOICE, FIELD_VISIBILITY_INSURANCE_PROVIDER, FIELD_VISIBILITY_RECOMMENDATION,
  FIELD_VISIBILITY_MEDICAL_RECORD, FIELD_VISIBILITY_WARD, FIELD_VISIBILITY_ADMISSION, FIELD_VISIBILITY_CURRENCY_RATE,
  FIELD_VISIBILITY_AUTO_BILLING_RULE, FIELD_VISIBILITY_MESSAGE, FIELD_VISIBILITY_MESSAGE_ATTACHMENT, FIELD_VISIBILITY_CONVERSATION,
  FIELD_VISIBILITY_TRIAGE_RECORD, FIELD_VISIBILITY_PAYMENT, FIELD_VISIBILITY_ORGANIZATION_PLAN, FIELD_VISIBILITY_EKG_RECORD,
  FIELD_VISIBILITY_DEPARTMENT_STOCK, FIELD_VISIBILITY_REFUND_TRANSACTION,   FIELD_VISIBILITY_PERMISSION, FIELD_VISIBILITY_ROLE_PERMISSION,
  FIELD_VISIBILITY_PATIENT_CHART_CACHE, FIELD_VISIBILITY_PATIENT_CHART_NOTE, FIELD_VISIBILITY_PATIENT_CHART_VIEW_LOG,
  FIELD_VISIBILITY_FINANCIAL_LEDGER

} from "./fieldVisibility.js";

/* -------------------- Init containers -------------------- */
const FIELD_LABELS = {};
const FIELD_ORDER = {};
const FIELD_DEFAULTS = {};
const FIELD_VISIBILITY = {};

/* -------------------- Organization -------------------- */
FIELD_LABELS.organization = FIELD_LABELS_ORGANIZATION;
FIELD_ORDER.organization = FIELD_ORDER_ORGANIZATION;
FIELD_DEFAULTS.organization = FIELD_DEFAULTS_ORGANIZATION;
FIELD_VISIBILITY.organization = FIELD_VISIBILITY_ORGANIZATION;

/* -------------------- Facility -------------------- */
FIELD_LABELS.facility = FIELD_LABELS_FACILITY;
FIELD_ORDER.facility = FIELD_ORDER_FACILITY;
FIELD_DEFAULTS.facility = FIELD_DEFAULTS_FACILITY;
FIELD_VISIBILITY.facility = FIELD_VISIBILITY_FACILITY;

/* -------------------- Role -------------------- */
FIELD_LABELS.role = FIELD_LABELS_ROLE;
FIELD_ORDER.role = FIELD_ORDER_ROLE;
FIELD_DEFAULTS.role = FIELD_DEFAULTS_ROLE;
FIELD_VISIBILITY.role = FIELD_VISIBILITY_ROLE;

/* -------------------- User -------------------- */
FIELD_LABELS.user = FIELD_LABELS_USER;
FIELD_ORDER.user = FIELD_ORDER_USER;
FIELD_DEFAULTS.user = FIELD_DEFAULTS_USER;
FIELD_VISIBILITY.user = FIELD_VISIBILITY_USER;

/* -------------------- Permission -------------------- */
FIELD_LABELS.permission = FIELD_LABELS_PERMISSION;
FIELD_ORDER.permission = FIELD_ORDER_PERMISSION;
FIELD_DEFAULTS.permission = FIELD_DEFAULTS_PERMISSION;
FIELD_VISIBILITY.permission = FIELD_VISIBILITY_PERMISSION;

/* -------------------- Role Permission -------------------- */
FIELD_LABELS.role_permission = FIELD_LABELS_ROLE_PERMISSION;
FIELD_ORDER.role_permission = FIELD_ORDER_ROLE_PERMISSION;
FIELD_DEFAULTS.role_permission = FIELD_DEFAULTS_ROLE_PERMISSION;
FIELD_VISIBILITY.role_permission = FIELD_VISIBILITY_ROLE_PERMISSION;

/* -------------------- User Facility -------------------- */
FIELD_LABELS.user_facility = FIELD_LABELS_USER_FACILITY;
FIELD_ORDER.user_facility = FIELD_ORDER_USER_FACILITY;
FIELD_DEFAULTS.user_facility = FIELD_DEFAULTS_USER_FACILITY;
FIELD_VISIBILITY.user_facility = FIELD_VISIBILITY_USER_FACILITY;

/* -------------------- Department -------------------- */
FIELD_LABELS.department = FIELD_LABELS_DEPARTMENT;
FIELD_ORDER.department = FIELD_ORDER_DEPARTMENT;
FIELD_DEFAULTS.department = FIELD_DEFAULTS_DEPARTMENT;
FIELD_VISIBILITY.department = FIELD_VISIBILITY_DEPARTMENT;

/* -------------------- Employee -------------------- */
FIELD_LABELS.employee = FIELD_LABELS_EMPLOYEE;
FIELD_ORDER.employee = FIELD_ORDER_EMPLOYEE;
FIELD_DEFAULTS.employee = FIELD_DEFAULTS_EMPLOYEE;
FIELD_VISIBILITY.employee = FIELD_VISIBILITY_EMPLOYEE;

/* -------------------- Feature Module -------------------- */
FIELD_LABELS.feature_module = FIELD_LABELS_FEATURE_MODULE;
FIELD_ORDER.feature_module = FIELD_ORDER_FEATURE_MODULE;
FIELD_DEFAULTS.feature_module = FIELD_DEFAULTS_FEATURE_MODULE;
FIELD_VISIBILITY.feature_module = FIELD_VISIBILITY_FEATURE_MODULE;

/* -------------------- Feature Access -------------------- */
FIELD_LABELS.feature_access = FIELD_LABELS_FEATURE_ACCESS;
FIELD_ORDER.feature_access = FIELD_ORDER_FEATURE_ACCESS;
FIELD_DEFAULTS.feature_access = FIELD_DEFAULTS_FEATURE_ACCESS;
FIELD_VISIBILITY.feature_access = FIELD_VISIBILITY_FEATURE_ACCESS;

/* -------------------- Vital -------------------- */
FIELD_LABELS.vital = FIELD_LABELS_VITAL;
FIELD_ORDER.vital = FIELD_ORDER_VITAL;
FIELD_DEFAULTS.vital = FIELD_DEFAULTS_VITAL;
FIELD_VISIBILITY.vital = FIELD_VISIBILITY_VITAL;

/* -------------------- Consultation Staff -------------------- */
FIELD_LABELS.consultation_staff = FIELD_LABELS_CONSULTATION_STAFF;
FIELD_ORDER.consultation_staff = FIELD_ORDER_CONSULTATION_STAFF;
FIELD_DEFAULTS.consultation_staff = FIELD_DEFAULTS_CONSULTATION_STAFF;
FIELD_VISIBILITY.consultation_staff = FIELD_VISIBILITY_CONSULTATION_STAFF;

/* -------------------- Patient -------------------- */
FIELD_LABELS.patient = FIELD_LABELS_PATIENT;
FIELD_ORDER.patient = FIELD_ORDER_PATIENT;
FIELD_DEFAULTS.patient = FIELD_DEFAULTS_PATIENT;
FIELD_VISIBILITY.patient = FIELD_VISIBILITY_PATIENT;

/* -------------------- Department Stock -------------------- */
FIELD_LABELS.department_stock = FIELD_LABELS_DEPARTMENT_STOCK;
FIELD_ORDER.department_stock = FIELD_ORDER_DEPARTMENT_STOCK;
FIELD_DEFAULTS.department_stock = FIELD_DEFAULTS_DEPARTMENT_STOCK;
FIELD_VISIBILITY.department_stock = FIELD_VISIBILITY_DEPARTMENT_STOCK;

/* -------------------- Billable Item Price History -------------------- */
FIELD_LABELS.billable_item_price_history = FIELD_LABELS_BILLABLE_ITEM_PRICE_HISTORY;
FIELD_ORDER.billable_item_price_history = FIELD_ORDER_BILLABLE_ITEM_PRICE_HISTORY;
FIELD_DEFAULTS.billable_item_price_history = FIELD_DEFAULTS_BILLABLE_ITEM_PRICE_HISTORY;
FIELD_VISIBILITY.billable_item_price_history = FIELD_VISIBILITY_BILLABLE_ITEM_PRICE_HISTORY;

/* -------------------- Facility Branding -------------------- */
FIELD_LABELS.facility_branding = FIELD_LABELS_FACILITY_BRANDING;
FIELD_ORDER.facility_branding = FIELD_ORDER_FACILITY_BRANDING;
FIELD_DEFAULTS.facility_branding = FIELD_DEFAULTS_FACILITY_BRANDING;
FIELD_VISIBILITY.facility_branding = FIELD_VISIBILITY_FACILITY_BRANDING;

/* -------------------- Letterhead Template -------------------- */
FIELD_LABELS.letterhead_template = FIELD_LABELS_LETTERHEAD_TEMPLATE;
FIELD_ORDER.letterhead_template = FIELD_ORDER_LETTERHEAD_TEMPLATE;
FIELD_DEFAULTS.letterhead_template = FIELD_DEFAULTS_LETTERHEAD_TEMPLATE;
FIELD_VISIBILITY.letterhead_template = FIELD_VISIBILITY_LETTERHEAD_TEMPLATE;

/* -------------------- Organization Branding -------------------- */
FIELD_LABELS.organization_branding = FIELD_LABELS_ORGANIZATION_BRANDING;
FIELD_ORDER.organization_branding = FIELD_ORDER_ORGANIZATION_BRANDING;
FIELD_DEFAULTS.organization_branding = FIELD_DEFAULTS_ORGANIZATION_BRANDING;
FIELD_VISIBILITY.organization_branding = FIELD_VISIBILITY_ORGANIZATION_BRANDING;

/* -------------------- Plan -------------------- */
FIELD_LABELS.plan = FIELD_LABELS_PLAN;
FIELD_ORDER.plan = FIELD_ORDER_PLAN;
FIELD_DEFAULTS.plan = FIELD_DEFAULTS_PLAN;
FIELD_VISIBILITY.plan = FIELD_VISIBILITY_PLAN;

/* -------------------- Stock Request -------------------- */
FIELD_LABELS.stock_request = FIELD_LABELS_STOCK_REQUEST;
FIELD_ORDER.stock_request = FIELD_ORDER_STOCK_REQUEST;
FIELD_DEFAULTS.stock_request = FIELD_DEFAULTS_STOCK_REQUEST;
FIELD_VISIBILITY.stock_request = FIELD_VISIBILITY_STOCK_REQUEST;

/* -------------------- Stock Request Item -------------------- */
FIELD_LABELS.stock_request_item = FIELD_LABELS_STOCK_REQUEST_ITEM;
FIELD_ORDER.stock_request_item = FIELD_ORDER_STOCK_REQUEST_ITEM;
FIELD_DEFAULTS.stock_request_item = FIELD_DEFAULTS_STOCK_REQUEST_ITEM;
FIELD_VISIBILITY.stock_request_item = FIELD_VISIBILITY_STOCK_REQUEST_ITEM;
/* -------------------- Billable Item -------------------- */
FIELD_LABELS.billable_item = FIELD_LABELS_BILLABLE_ITEM;
FIELD_ORDER.billable_item = FIELD_ORDER_BILLABLE_ITEM;
FIELD_DEFAULTS.billable_item = FIELD_DEFAULTS_BILLABLE_ITEM;
FIELD_VISIBILITY.billable_item = FIELD_VISIBILITY_BILLABLE_ITEM;

/* -------------------- Consultation -------------------- */
FIELD_LABELS.consultation = FIELD_LABELS_CONSULTATION;
FIELD_ORDER.consultation = FIELD_ORDER_CONSULTATION;
FIELD_DEFAULTS.consultation = FIELD_DEFAULTS_CONSULTATION;
FIELD_VISIBILITY.consultation = FIELD_VISIBILITY_CONSULTATION;

/* -------------------- Deposit -------------------- */
FIELD_LABELS.deposit = FIELD_LABELS_DEPOSIT;
FIELD_ORDER.deposit = FIELD_ORDER_DEPOSIT;
FIELD_DEFAULTS.deposit = FIELD_DEFAULTS_DEPOSIT;
FIELD_VISIBILITY.deposit = FIELD_VISIBILITY_DEPOSIT;
/* -------------------- Financial Ledger -------------------- */

FIELD_LABELS.financial_ledger = FIELD_LABELS_FINANCIAL_LEDGER;
FIELD_ORDER.financial_ledger = FIELD_ORDER_FINANCIAL_LEDGER;
FIELD_DEFAULTS.financial_ledger = FIELD_DEFAULTS_FINANCIAL_LEDGER;
FIELD_VISIBILITY.financial_ledger = FIELD_VISIBILITY_FINANCIAL_LEDGER;

/* -------------------- Invoice Item -------------------- */
FIELD_LABELS.invoice_item = FIELD_LABELS_INVOICE_ITEM;
FIELD_ORDER.invoice_item = FIELD_ORDER_INVOICE_ITEM;
FIELD_DEFAULTS.invoice_item = FIELD_DEFAULTS_INVOICE_ITEM;
FIELD_VISIBILITY.invoice_item = FIELD_VISIBILITY_INVOICE_ITEM;

/* -------------------- Refund -------------------- */
FIELD_LABELS.refund = FIELD_LABELS_REFUND;
FIELD_ORDER.refund = FIELD_ORDER_REFUND;
FIELD_DEFAULTS.refund = FIELD_DEFAULTS_REFUND;
FIELD_VISIBILITY.refund = FIELD_VISIBILITY_REFUND;
/* -------------------- Refund Transaction -------------------- */
FIELD_LABELS.refund_transaction = FIELD_LABELS_REFUND_TRANSACTION;
FIELD_ORDER.refund_transaction = FIELD_ORDER_REFUND_TRANSACTION;
FIELD_DEFAULTS.refund_transaction = FIELD_DEFAULTS_REFUND_TRANSACTION;
FIELD_VISIBILITY.refund_transaction = FIELD_VISIBILITY_REFUND_TRANSACTION;

/* -------------------- Refund Deposit -------------------- */
FIELD_LABELS.refund_deposit = FIELD_LABELS_REFUND_DEPOSIT;
FIELD_ORDER.refund_deposit = FIELD_ORDER_REFUND_DEPOSIT;
FIELD_DEFAULTS.refund_deposit = FIELD_DEFAULTS_REFUND_DEPOSIT;
FIELD_VISIBILITY.refund_deposit = FIELD_VISIBILITY_REFUND_DEPOSIT;


/* -------------------- Registration Log -------------------- */
FIELD_LABELS.registration_log = FIELD_LABELS_REGISTRATION_LOG;
FIELD_ORDER.registration_log = FIELD_ORDER_REGISTRATION_LOG;
FIELD_DEFAULTS.registration_log = FIELD_DEFAULTS_REGISTRATION_LOG;
FIELD_VISIBILITY.registration_log = FIELD_VISIBILITY_REGISTRATION_LOG;

/* -------------------- Plan Module -------------------- */
FIELD_LABELS.plan_module = FIELD_LABELS_PLAN_MODULE;
FIELD_ORDER.plan_module = FIELD_ORDER_PLAN_MODULE;
FIELD_DEFAULTS.plan_module = FIELD_DEFAULTS_PLAN_MODULE;
FIELD_VISIBILITY.plan_module = FIELD_VISIBILITY_PLAN_MODULE;

/* -------------------- Central Stock -------------------- */
FIELD_LABELS.central_stock = FIELD_LABELS_CENTRAL_STOCK;
FIELD_ORDER.central_stock = FIELD_ORDER_CENTRAL_STOCK;
FIELD_DEFAULTS.central_stock = FIELD_DEFAULTS_CENTRAL_STOCK;
FIELD_VISIBILITY.central_stock = FIELD_VISIBILITY_CENTRAL_STOCK;

/* -------------------- Master Item -------------------- */
FIELD_LABELS.master_item = FIELD_LABELS_MASTER_ITEM;
FIELD_ORDER.master_item = FIELD_ORDER_MASTER_ITEM;
FIELD_DEFAULTS.master_item = FIELD_DEFAULTS_MASTER_ITEM;
FIELD_VISIBILITY.master_item = FIELD_VISIBILITY_MASTER_ITEM;

/* -------------------- Supplier -------------------- */
FIELD_LABELS.supplier = FIELD_LABELS_SUPPLIER;
FIELD_ORDER.supplier = FIELD_ORDER_SUPPLIER;
FIELD_DEFAULTS.supplier = FIELD_DEFAULTS_SUPPLIER;
FIELD_VISIBILITY.supplier = FIELD_VISIBILITY_SUPPLIER;

/* -------------------- Master Item Category -------------------- */
FIELD_LABELS.master_item_category = FIELD_LABELS_MASTER_ITEM_CATEGORY;
FIELD_ORDER.master_item_category = FIELD_ORDER_MASTER_ITEM_CATEGORY;
FIELD_DEFAULTS.master_item_category = FIELD_DEFAULTS_MASTER_ITEM_CATEGORY;
FIELD_VISIBILITY.master_item_category = FIELD_VISIBILITY_MASTER_ITEM_CATEGORY;

/* -------------------- Stock Adjustment -------------------- */
FIELD_LABELS.stock_adjustment = FIELD_LABELS_STOCK_ADJUSTMENT;
FIELD_ORDER.stock_adjustment = FIELD_ORDER_STOCK_ADJUSTMENT;
FIELD_DEFAULTS.stock_adjustment = FIELD_DEFAULTS_STOCK_ADJUSTMENT;
FIELD_VISIBILITY.stock_adjustment = FIELD_VISIBILITY_STOCK_ADJUSTMENT;

/* -------------------- Appointment -------------------- */
FIELD_LABELS.appointment = FIELD_LABELS_APPOINTMENT;
FIELD_ORDER.appointment = FIELD_ORDER_APPOINTMENT;
FIELD_DEFAULTS.appointment = FIELD_DEFAULTS_APPOINTMENT;
FIELD_VISIBILITY.appointment = FIELD_VISIBILITY_APPOINTMENT;

/* -------------------- Lab Request -------------------- */
FIELD_LABELS.lab_request = FIELD_LABELS_LAB_REQUEST;
FIELD_ORDER.lab_request = FIELD_ORDER_LAB_REQUEST;
FIELD_DEFAULTS.lab_request = FIELD_DEFAULTS_LAB_REQUEST;
FIELD_VISIBILITY.lab_request = FIELD_VISIBILITY_LAB_REQUEST;

/* -------------------- Lab Request Item -------------------- */
FIELD_LABELS.lab_request_item = FIELD_LABELS_LAB_REQUEST_ITEM;
FIELD_ORDER.lab_request_item = FIELD_ORDER_LAB_REQUEST_ITEM;
FIELD_DEFAULTS.lab_request_item = FIELD_DEFAULTS_LAB_REQUEST_ITEM;
FIELD_VISIBILITY.lab_request_item = FIELD_VISIBILITY_LAB_REQUEST_ITEM;

/* -------------------- Prescription -------------------- */
FIELD_LABELS.prescription = FIELD_LABELS_PRESCRIPTION;
FIELD_ORDER.prescription = FIELD_ORDER_PRESCRIPTION;
FIELD_DEFAULTS.prescription = FIELD_DEFAULTS_PRESCRIPTION;
FIELD_VISIBILITY.prescription = FIELD_VISIBILITY_PRESCRIPTION;

/* -------------------- Lab Supply -------------------- */
FIELD_LABELS.lab_supply = FIELD_LABELS_LAB_SUPPLY;
FIELD_ORDER.lab_supply = FIELD_ORDER_LAB_SUPPLY;
FIELD_DEFAULTS.lab_supply = FIELD_DEFAULTS_LAB_SUPPLY;
FIELD_VISIBILITY.lab_supply = FIELD_VISIBILITY_LAB_SUPPLY;

/* -------------------- Prescription Item -------------------- */
FIELD_LABELS.prescription_item = FIELD_LABELS_PRESCRIPTION_ITEM;
FIELD_ORDER.prescription_item = FIELD_ORDER_PRESCRIPTION_ITEM;
FIELD_DEFAULTS.prescription_item = FIELD_DEFAULTS_PRESCRIPTION_ITEM;
FIELD_VISIBILITY.prescription_item = FIELD_VISIBILITY_PRESCRIPTION_ITEM;

/* -------------------- Surgery -------------------- */
FIELD_LABELS.surgery = FIELD_LABELS_SURGERY;
FIELD_ORDER.surgery = FIELD_ORDER_SURGERY;
FIELD_DEFAULTS.surgery = FIELD_DEFAULTS_SURGERY;
FIELD_VISIBILITY.surgery = FIELD_VISIBILITY_SURGERY;

/* -------------------- Bed -------------------- */
FIELD_LABELS.bed = FIELD_LABELS_BED;
FIELD_ORDER.bed = FIELD_ORDER_BED;
FIELD_DEFAULTS.bed = FIELD_DEFAULTS_BED;
FIELD_VISIBILITY.bed = FIELD_VISIBILITY_BED;

/* -------------------- Employee Shift -------------------- */
FIELD_LABELS.employee_shift = FIELD_LABELS_EMPLOYEE_SHIFT;
FIELD_ORDER.employee_shift = FIELD_ORDER_EMPLOYEE_SHIFT;
FIELD_DEFAULTS.employee_shift = FIELD_DEFAULTS_EMPLOYEE_SHIFT;
FIELD_VISIBILITY.employee_shift = FIELD_VISIBILITY_EMPLOYEE_SHIFT;

/* -------------------- Access Violation Log -------------------- */
FIELD_LABELS.access_violation_log = FIELD_LABELS_ACCESS_VIOLATION_LOG;
FIELD_ORDER.access_violation_log = FIELD_ORDER_ACCESS_VIOLATION_LOG;
FIELD_DEFAULTS.access_violation_log = FIELD_DEFAULTS_ACCESS_VIOLATION_LOG;
FIELD_VISIBILITY.access_violation_log = FIELD_VISIBILITY_ACCESS_VIOLATION_LOG;

/* -------------------- Delivery Record -------------------- */
FIELD_LABELS.delivery_record = FIELD_LABELS_DELIVERY_RECORD;
FIELD_ORDER.delivery_record = FIELD_ORDER_DELIVERY_RECORD;
FIELD_DEFAULTS.delivery_record = FIELD_DEFAULTS_DELIVERY_RECORD;
FIELD_VISIBILITY.delivery_record = FIELD_VISIBILITY_DELIVERY_RECORD;

/* -------------------- Maternity Visit -------------------- */
FIELD_LABELS.maternity_visit = FIELD_LABELS_MATERNITY_VISIT;
FIELD_ORDER.maternity_visit = FIELD_ORDER_MATERNITY_VISIT;
FIELD_DEFAULTS.maternity_visit = FIELD_DEFAULTS_MATERNITY_VISIT;
FIELD_VISIBILITY.maternity_visit = FIELD_VISIBILITY_MATERNITY_VISIT;

/* -------------------- Pharmacy Transaction -------------------- */
FIELD_LABELS.pharmacy_transaction = FIELD_LABELS_PHARMACY_TRANSACTION;
FIELD_ORDER.pharmacy_transaction = FIELD_ORDER_PHARMACY_TRANSACTION;
FIELD_DEFAULTS.pharmacy_transaction = FIELD_DEFAULTS_PHARMACY_TRANSACTION;
FIELD_VISIBILITY.pharmacy_transaction = FIELD_VISIBILITY_PHARMACY_TRANSACTION;

/* -------------------- System Audit Log -------------------- */
FIELD_LABELS.system_audit_log = FIELD_LABELS_SYSTEM_AUDIT_LOG;
FIELD_ORDER.system_audit_log = FIELD_ORDER_SYSTEM_AUDIT_LOG;
FIELD_DEFAULTS.system_audit_log = FIELD_DEFAULTS_SYSTEM_AUDIT_LOG;
FIELD_VISIBILITY.system_audit_log = FIELD_VISIBILITY_SYSTEM_AUDIT_LOG;

/* -------------------- Insurance Claim -------------------- */
FIELD_LABELS.insurance_claim = FIELD_LABELS_INSURANCE_CLAIM;
FIELD_ORDER.insurance_claim = FIELD_ORDER_INSURANCE_CLAIM;
FIELD_DEFAULTS.insurance_claim = FIELD_DEFAULTS_INSURANCE_CLAIM;
FIELD_VISIBILITY.insurance_claim = FIELD_VISIBILITY_INSURANCE_CLAIM;

/* -------------------- Newborn Record -------------------- */
FIELD_LABELS.newborn_record = FIELD_LABELS_NEWBORN_RECORD;
FIELD_ORDER.newborn_record = FIELD_ORDER_NEWBORN_RECORD;
FIELD_DEFAULTS.newborn_record = FIELD_DEFAULTS_NEWBORN_RECORD;
FIELD_VISIBILITY.newborn_record = FIELD_VISIBILITY_NEWBORN_RECORD;

/* -------------------- Procedure Record -------------------- */
FIELD_LABELS.procedure_record = FIELD_LABELS_PROCEDURE_RECORD;
FIELD_ORDER.procedure_record = FIELD_ORDER_PROCEDURE_RECORD;
FIELD_DEFAULTS.procedure_record = FIELD_DEFAULTS_PROCEDURE_RECORD;
FIELD_VISIBILITY.procedure_record = FIELD_VISIBILITY_PROCEDURE_RECORD;

/* -------------------- Room -------------------- */
FIELD_LABELS.room = FIELD_LABELS_ROOM;
FIELD_ORDER.room = FIELD_ORDER_ROOM;
FIELD_DEFAULTS.room = FIELD_DEFAULTS_ROOM;
FIELD_VISIBILITY.room = FIELD_VISIBILITY_ROOM;

/* -------------------- Login Audit -------------------- */
FIELD_LABELS.login_audit = FIELD_LABELS_LOGIN_AUDIT;
FIELD_ORDER.login_audit = FIELD_ORDER_LOGIN_AUDIT;
FIELD_DEFAULTS.login_audit = FIELD_DEFAULTS_LOGIN_AUDIT;
FIELD_VISIBILITY.login_audit = FIELD_VISIBILITY_LOGIN_AUDIT;
/* -------------------- Nursing Note -------------------- */
FIELD_LABELS.nursing_note = FIELD_LABELS_NURSING_NOTE;
FIELD_ORDER.nursing_note = FIELD_ORDER_NURSING_NOTE;
FIELD_DEFAULTS.nursing_note = FIELD_DEFAULTS_NURSING_NOTE;
FIELD_VISIBILITY.nursing_note = FIELD_VISIBILITY_NURSING_NOTE;

/* -------------------- Discount -------------------- */
FIELD_LABELS.discount = FIELD_LABELS_DISCOUNT;
FIELD_ORDER.discount = FIELD_ORDER_DISCOUNT;
FIELD_DEFAULTS.discount = FIELD_DEFAULTS_DISCOUNT;
FIELD_VISIBILITY.discount = FIELD_VISIBILITY_DISCOUNT;

/* -------------------- Discount Waiver -------------------- */
FIELD_LABELS.discount_waiver = FIELD_LABELS_DISCOUNT_WAIVER;
FIELD_ORDER.discount_waiver = FIELD_ORDER_DISCOUNT_WAIVER;
FIELD_DEFAULTS.discount_waiver = FIELD_DEFAULTS_DISCOUNT_WAIVER;
FIELD_VISIBILITY.discount_waiver = FIELD_VISIBILITY_DISCOUNT_WAIVER;

/* -------------------- Discount Policy -------------------- */
FIELD_LABELS.discount_policy = FIELD_LABELS_DISCOUNT_POLICY;
FIELD_ORDER.discount_policy = FIELD_ORDER_DISCOUNT_POLICY;
FIELD_DEFAULTS.discount_policy = FIELD_DEFAULTS_DISCOUNT_POLICY;
FIELD_VISIBILITY.discount_policy = FIELD_VISIBILITY_DISCOUNT_POLICY;

/* -------------------- Insurance PreAuthorization -------------------- */
FIELD_LABELS.insurance_preauthorization = FIELD_LABELS_INSURANCE_PREAUTHORIZATION;
FIELD_ORDER.insurance_preauthorization = FIELD_ORDER_INSURANCE_PREAUTHORIZATION;
FIELD_DEFAULTS.insurance_preauthorization = FIELD_DEFAULTS_INSURANCE_PREAUTHORIZATION;
FIELD_VISIBILITY.insurance_preauthorization = FIELD_VISIBILITY_INSURANCE_PREAUTHORIZATION;

/* -------------------- Lab Result -------------------- */
FIELD_LABELS.lab_result = FIELD_LABELS_LAB_RESULT;
FIELD_ORDER.lab_result = FIELD_ORDER_LAB_RESULT;
FIELD_DEFAULTS.lab_result = FIELD_DEFAULTS_LAB_RESULT;
FIELD_VISIBILITY.lab_result = FIELD_VISIBILITY_LAB_RESULT;

/* -------------------- Radiology Record -------------------- */
FIELD_LABELS.radiology_record = FIELD_LABELS_RADIOLOGY_RECORD;
FIELD_ORDER.radiology_record = FIELD_ORDER_RADIOLOGY_RECORD;
FIELD_DEFAULTS.radiology_record = FIELD_DEFAULTS_RADIOLOGY_RECORD;
FIELD_VISIBILITY.radiology_record = FIELD_VISIBILITY_RADIOLOGY_RECORD;

/* -------------------- Ultrasound Record -------------------- */
FIELD_LABELS.ultrasound_record = FIELD_LABELS_ULTRASOUND_RECORD;
FIELD_ORDER.ultrasound_record = FIELD_ORDER_ULTRASOUND_RECORD;
FIELD_DEFAULTS.ultrasound_record = FIELD_DEFAULTS_ULTRASOUND_RECORD;
FIELD_VISIBILITY.ultrasound_record = FIELD_VISIBILITY_ULTRASOUND_RECORD;

/* -------------------- EKG Record -------------------- */
FIELD_LABELS.ekg_record = FIELD_LABELS_EKG_RECORD;
FIELD_ORDER.ekg_record = FIELD_ORDER_EKG_RECORD;
FIELD_DEFAULTS.ekg_record = FIELD_DEFAULTS_EKG_RECORD;
FIELD_VISIBILITY.ekg_record = FIELD_VISIBILITY_EKG_RECORD;

/* -------------------- Invoice -------------------- */
FIELD_LABELS.invoice = FIELD_LABELS_INVOICE;
FIELD_ORDER.invoice = FIELD_ORDER_INVOICE;
FIELD_DEFAULTS.invoice = FIELD_DEFAULTS_INVOICE;
FIELD_VISIBILITY.invoice = FIELD_VISIBILITY_INVOICE;

/* -------------------- Insurance Provider -------------------- */
FIELD_LABELS.insurance_provider = FIELD_LABELS_INSURANCE_PROVIDER;
FIELD_ORDER.insurance_provider = FIELD_ORDER_INSURANCE_PROVIDER;
FIELD_DEFAULTS.insurance_provider = FIELD_DEFAULTS_INSURANCE_PROVIDER;
FIELD_VISIBILITY.insurance_provider = FIELD_VISIBILITY_INSURANCE_PROVIDER;

/* -------------------- Recommendation -------------------- */
FIELD_LABELS.recommendation = FIELD_LABELS_RECOMMENDATION;
FIELD_ORDER.recommendation = FIELD_ORDER_RECOMMENDATION;
FIELD_DEFAULTS.recommendation = FIELD_DEFAULTS_RECOMMENDATION;
FIELD_VISIBILITY.recommendation = FIELD_VISIBILITY_RECOMMENDATION;

/* -------------------- Medical Record -------------------- */
FIELD_LABELS.medical_record = FIELD_LABELS_MEDICAL_RECORD;
FIELD_ORDER.medical_record = FIELD_ORDER_MEDICAL_RECORD;
FIELD_DEFAULTS.medical_record = FIELD_DEFAULTS_MEDICAL_RECORD;
FIELD_VISIBILITY.medical_record = FIELD_VISIBILITY_MEDICAL_RECORD;
/* -------------------- Ward -------------------- */
FIELD_LABELS.ward = FIELD_LABELS_WARD;
FIELD_ORDER.ward = FIELD_ORDER_WARD;
FIELD_DEFAULTS.ward = FIELD_DEFAULTS_WARD;
FIELD_VISIBILITY.ward = FIELD_VISIBILITY_WARD;

/* -------------------- Admission -------------------- */
FIELD_LABELS.admission = FIELD_LABELS_ADMISSION;
FIELD_ORDER.admission = FIELD_ORDER_ADMISSION;
FIELD_DEFAULTS.admission = FIELD_DEFAULTS_ADMISSION;
FIELD_VISIBILITY.admission = FIELD_VISIBILITY_ADMISSION;

/* -------------------- Currency Rate -------------------- */
FIELD_LABELS.currency_rate = FIELD_LABELS_CURRENCY_RATE;
FIELD_ORDER.currency_rate = FIELD_ORDER_CURRENCY_RATE;
FIELD_DEFAULTS.currency_rate = FIELD_DEFAULTS_CURRENCY_RATE;
FIELD_VISIBILITY.currency_rate = FIELD_VISIBILITY_CURRENCY_RATE;

/* -------------------- Auto Billing Rule -------------------- */
FIELD_LABELS.auto_billing_rule = FIELD_LABELS_AUTO_BILLING_RULE;
FIELD_ORDER.auto_billing_rule = FIELD_ORDER_AUTO_BILLING_RULE;
FIELD_DEFAULTS.auto_billing_rule = FIELD_DEFAULTS_AUTO_BILLING_RULE;
FIELD_VISIBILITY.auto_billing_rule = FIELD_VISIBILITY_AUTO_BILLING_RULE;

/* -------------------- Message -------------------- */
FIELD_LABELS.message = FIELD_LABELS_MESSAGE;
FIELD_ORDER.message = FIELD_ORDER_MESSAGE;
FIELD_DEFAULTS.message = FIELD_DEFAULTS_MESSAGE;
FIELD_VISIBILITY.message = FIELD_VISIBILITY_MESSAGE;

/* -------------------- Message Attachment -------------------- */
FIELD_LABELS.message_attachment = FIELD_LABELS_MESSAGE_ATTACHMENT;
FIELD_ORDER.message_attachment = FIELD_ORDER_MESSAGE_ATTACHMENT;
FIELD_DEFAULTS.message_attachment = FIELD_DEFAULTS_MESSAGE_ATTACHMENT;
FIELD_VISIBILITY.message_attachment = FIELD_VISIBILITY_MESSAGE_ATTACHMENT;

/* -------------------- Conversation -------------------- */
FIELD_LABELS.conversation = FIELD_LABELS_CONVERSATION;
FIELD_ORDER.conversation = FIELD_ORDER_CONVERSATION;
FIELD_DEFAULTS.conversation = FIELD_DEFAULTS_CONVERSATION;
FIELD_VISIBILITY.conversation = FIELD_VISIBILITY_CONVERSATION;

/* -------------------- Triage Record -------------------- */
FIELD_LABELS.triage_record = FIELD_LABELS_TRIAGE_RECORD;
FIELD_ORDER.triage_record = FIELD_ORDER_TRIAGE_RECORD;
FIELD_DEFAULTS.triage_record = FIELD_DEFAULTS_TRIAGE_RECORD;
FIELD_VISIBILITY.triage_record = FIELD_VISIBILITY_TRIAGE_RECORD;

/* -------------------- Payment -------------------- */
FIELD_LABELS.payment = FIELD_LABELS_PAYMENT;
FIELD_ORDER.payment = FIELD_ORDER_PAYMENT;
FIELD_DEFAULTS.payment = FIELD_DEFAULTS_PAYMENT;
FIELD_VISIBILITY.payment = FIELD_VISIBILITY_PAYMENT;

/* -------------------- Organization Plan -------------------- */
FIELD_LABELS.organization_plan = FIELD_LABELS_ORGANIZATION_PLAN;
FIELD_ORDER.organization_plan = FIELD_ORDER_ORGANIZATION_PLAN;
FIELD_DEFAULTS.organization_plan = FIELD_DEFAULTS_ORGANIZATION_PLAN;
FIELD_VISIBILITY.organization_plan = FIELD_VISIBILITY_ORGANIZATION_PLAN;

/* -------------------- Patient Chart Cache -------------------- */
FIELD_LABELS.patient_chart_cache = FIELD_LABELS_PATIENT_CHART_CACHE;
FIELD_ORDER.patient_chart_cache = FIELD_ORDER_PATIENT_CHART_CACHE;
FIELD_DEFAULTS.patient_chart_cache = FIELD_DEFAULTS_PATIENT_CHART_CACHE;
FIELD_VISIBILITY.patient_chart_cache = FIELD_VISIBILITY_PATIENT_CHART_CACHE;

/* -------------------- Patient Chart Note -------------------- */
FIELD_LABELS.patient_chart_note = FIELD_LABELS_PATIENT_CHART_NOTE;
FIELD_ORDER.patient_chart_note = FIELD_ORDER_PATIENT_CHART_NOTE;
FIELD_DEFAULTS.patient_chart_note = FIELD_DEFAULTS_PATIENT_CHART_NOTE;
FIELD_VISIBILITY.patient_chart_note = FIELD_VISIBILITY_PATIENT_CHART_NOTE;

/* -------------------- Patient Chart View Log -------------------- */
FIELD_LABELS.patient_chart_view_log = FIELD_LABELS_PATIENT_CHART_VIEW_LOG;
FIELD_ORDER.patient_chart_view_log = FIELD_ORDER_PATIENT_CHART_VIEW_LOG;
FIELD_DEFAULTS.patient_chart_view_log = FIELD_DEFAULTS_PATIENT_CHART_VIEW_LOG;
FIELD_VISIBILITY.patient_chart_view_log = FIELD_VISIBILITY_PATIENT_CHART_VIEW_LOG;

/* -------------------- Export -------------------- */
export {
  FIELD_LABELS,
  FIELD_ORDER,
  FIELD_DEFAULTS,
  FIELD_VISIBILITY
};
