version: "3.9"
services:
  db:
    image: postgres:16
    container_name: vg_postgres
    environment:
      POSTGRES_USER: vytal
      POSTGRES_PASSWORD: vytal
      POSTGRES_DB: vytalguard
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vytal -d vytalguard"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  pgdata:
