// 📁 frontend/js/modules/expenses/expense-receipt.js
// ============================================================================
// 🧾 Expense Receipt (FULL RECORD RANGE | FILTER-AWARE READY)
// 🔹 Clean currency handling
// 🔹 Audit-safe printedBy
// 🔹 Expense-aligned fields
// 🔹 No deposit/patient logic
// 🔹 Enterprise print output
// ============================================================================

import { printDocument } from "../../templates/printTemplate.js";

/* ============================================================ */
function formatDate(dateStr) {
  if (!dateStr) return "—";
  const d = new Date(dateStr);
  if (isNaN(d)) return dateStr;
  return d.toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "2-digit",
  });
}

/* ============================================================ */
function getPrintedBy(expense) {
  try {
    const authSession = JSON.parse(localStorage.getItem("authSession") || "{}");

    return (
      authSession?.name ||
      (expense?.createdBy
        ? `${expense.createdBy.first_name} ${expense.createdBy.last_name}`
        : null) ||
      localStorage.getItem("userName") ||
      "Unknown User"
    );
  } catch {
    return "Unknown User";
  }
}

/* ============================================================ */
function money(value) {
  return Number(value || 0).toFixed(2);
}

/* ============================================================ */
function buildExpenseReceiptHTML(expense) {
  const printedBy = getPrintedBy(expense);
  const printedAt = new Date().toLocaleString();

  return `
    <!-- 🏢 Facility -->
    <div style="margin-bottom:12px; font-size:13px;">
      <strong>Facility:</strong> ${expense.facility?.name || "—"}
    </div>

    <!-- 🔥 HEADER -->
    <div class="grid-2">

      <div>
        <div><strong>Account:</strong> ${
          expense.account?.name || "—"
        }</div>

        <div><strong>Category:</strong> ${
          expense.category || "—"
        }</div>
      </div>

      <div>
        <div><strong>Expense #:</strong> ${
          expense.expense_number || "—"
        }</div>

        <div><strong>Date:</strong> ${formatDate(
          expense.date
        )}</div>

        <div><strong>Status:</strong> ${expense.status || ""}</div>

        <div><strong>Currency:</strong> ${
          expense.currency || "—"
        }</div>
      </div>

    </div>

    <!-- 📦 DETAILS -->
    <h4 style="margin-top:18px;">Expense Details</h4>

    <table>
      <thead>
        <tr>
          <th>Description</th>
          <th>Value</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Payment Method</td>
          <td>${expense.payment_method || "—"}</td>
        </tr>
        <tr>
          <td>Description</td>
          <td>${expense.description || "—"}</td>
        </tr>
      </tbody>
    </table>

    <!-- 💵 TOTAL -->
    <div class="totals">
      <div class="final">
        <span>Total Expense:</span>
        <span>${money(expense.amount)}</span>
      </div>
    </div>

    <!-- 🕓 AUDIT -->
    <div style="margin-top:20px; font-size:11px;">
      Printed by: <strong>${printedBy}</strong><br/>
      Printed at: ${printedAt}
    </div>

    <!-- 🧾 FOOTER -->
    <div style="margin-top:15px; font-size:12px;">
      Expense record generated by system.
    </div>
  `;
}

/* ============================================================ */
export function printExpenseReceipt(expense) {
  const html = buildExpenseReceiptHTML(expense);

  printDocument(html, {
    title: "Expense Receipt",

    invoice: {
      organization: expense.organization,
      status: expense.status,
    },

    branding: JSON.parse(localStorage.getItem("branding") || "{}"),
  });
}